name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v2.0.0
        with:
          port: 8000
          cors: "*"

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: yarn install --frozen-lockfile
      - run: |
          cd apps/api
          yarn test
        env:
          TABLE: dummy
          GITHUB_CLIENT_ID: dummy
          GITHUB_CLIENT_SECRET: dummy
          GOOGLE_CLIENT_ID: dummy
          GOOGLE_CLIENT_SECRET: dummy
          ES_URL: http://localhost:9200
          ES_USERNAME: dummy
          ES_PASSWORD: dummy
          TESTER_TOPIC_ARN: dummy
          TOPIC_ARN: dummy
          S3_BUCKET_NAME: dummy
          SOCKET_ENDPOINT: dummy
          AWS_REGION: eu-central-1
